{
  LOGGER.error("Got exception in the channel to {}, connId {}",_server,getConnId(),cause);
  closeOnError(ctx,cause);
  releaseResources();
}
