{
  try {
    serverInstance.start();
  }
 catch (  final Exception e) {
    LOGGER.error("Caught exception",e);
  }
}
